notifications:
  email:
    - mig-travis@cern.ch
language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - pip install --use-mirrors pep8
  - if [[ $TRAVIS_PYTHON_VERSION != '2.5' ]]; then pip install --use-mirrors pylint; fi
  - curl -O -R -S -f -s https://raw.github.com/cern-mig/dev-tools/master/python/pylint.sh
  - curl -O -R -S -f -s https://raw.github.com/cern-mig/dev-tools/master/python/.pylintrc
# command to run tests
script:
  - pep8 auth test
  - sh pylint.sh auth test || echo "*ignored*"
  - python setup.py test
